# Generated by Django 5.2.7 on 2026-01-28 14:09

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q
from datetime import date
from collections import defaultdict


def generate_order_number_for_existing_orders(apps, schema_editor):
    """
    Generate order numbers for all existing orders that don't have one.
    This is needed before adding the unique constraint.
    """
    Order = apps.get_model('orders', 'Order')
    
    # Check if field exists (in case migration partially ran)
    try:
        # Get all orders without order_number
        orders_without_number = Order.objects.filter(
            Q(order_number__isnull=True) | Q(order_number='')
        )
    except Exception:
        # Field might not exist yet, skip
        return
    
    if not orders_without_number.exists():
        return  # No orders to update
    
    # Group orders by placed_at date
    orders_by_date = defaultdict(list)
    
    for order in orders_without_number:
        # Use placed_at date or created date
        if order.placed_at:
            order_date = order.placed_at.date()
        else:
            order_date = order.created.date() if hasattr(order, 'created') and order.created else date.today()
        orders_by_date[order_date].append(order)
    
    # Generate order numbers for each date group
    for order_date, orders in orders_by_date.items():
        date_str = order_date.strftime("%Y%m%d")
        prefix = f"ORD-{date_str}-"
        
        # Find existing order numbers for this date
        existing_numbers = Order.objects.filter(
            order_number__startswith=prefix
        ).exclude(
            Q(order_number__isnull=True) | Q(order_number='')
        ).values_list('order_number', flat=True)
        
        # Find max sequence for this date
        max_seq = 0
        if existing_numbers:
            for order_num in existing_numbers:
                try:
                    seq_part = order_num.split('-')[-1]
                    seq_num = int(seq_part)
                    max_seq = max(max_seq, seq_num)
                except (ValueError, IndexError):
                    continue
        
        # Assign order numbers to orders (sorted by created date for consistency)
        orders_sorted = sorted(orders, key=lambda o: o.created if hasattr(o, 'created') and o.created else o.id)
        
        for idx, order in enumerate(orders_sorted):
            next_seq = max_seq + idx + 1
            order.order_number = f"{prefix}{next_seq:05d}"
            order.save(update_fields=['order_number'])


def reverse_generate_order_numbers(apps, schema_editor):
    """
    Reverse migration - clear order numbers (optional, for rollback)
    """
    Order = apps.get_model('orders', 'Order')
    Order.objects.all().update(order_number='')


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_couponusage_coupon_max_discount_and_more"),
        ("user", "0003_address_is_guest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Add the field without unique constraint first (if it doesn't exist)
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True,
                db_index=False,  # Don't create index yet to avoid conflicts
                help_text="Auto-generated order number in format ORD-YYYYMMDD-XXXXX",
                max_length=20,
                null=True,  # Allow null temporarily
            ),
        ),
        # Step 2: Generate order numbers for existing orders
        migrations.RunPython(
            generate_order_number_for_existing_orders,
            reverse_generate_order_numbers,
        ),
        # Step 4: Make the field NOT NULL and UNIQUE
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Auto-generated order number in format ORD-YYYYMMDD-XXXXX",
                max_length=20,
                unique=True,
            ),
        ),
    ]
