# Generated by Django 5.2.7 on 2026-01-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_address_email_alter_address_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_guest",
            field=models.BooleanField(default=False),
        ),
    ]
