# Generated by Django 5.2.7 on 2026-02-04 10:10

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "last_modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Last modified",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="Is deleted"),
                ),
                (
                    "disabled",
                    models.BooleanField(default=False, verbose_name="Is disabled"),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Blog Tag",
                "verbose_name_plural": "Blog Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "last_modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Last modified",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="Is deleted"),
                ),
                (
                    "disabled",
                    models.BooleanField(default=False, verbose_name="Is disabled"),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "featured_video",
                    models.URLField(
                        blank=True,
                        help_text="Featured video URL for the blog post",
                        null=True,
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short summary or excerpt of the blog post",
                        max_length=500,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Full content of the blog post"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, help_text="Publication date and time", null=True
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tags for the blog post",
                        related_name="blogs",
                        to="blogs.blogtag",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created"],
            },
        ),
        migrations.CreateModel(
            name="BlogImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "last_modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Last modified",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="Is deleted"),
                ),
                (
                    "disabled",
                    models.BooleanField(default=False, verbose_name="Is disabled"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image for the blog post",
                        null=True,
                        upload_to="blogs/images/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alternative text for the image",
                        max_length=255,
                    ),
                ),
                (
                    "ordering",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which images should be displayed"
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="blogs.blog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Image",
                "verbose_name_plural": "Blog Images",
                "ordering": ["ordering", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["status", "is_active"], name="blogs_blog_status_4c7cbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["is_active"], name="blogs_blog_is_acti_23eb43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["published_at"], name="blogs_blog_publish_1caa21_idx"
            ),
        ),
    ]
