# Generated by Django 5.2.7 on 2026-02-04 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of the title",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(fields=["slug"], name="blogs_blog_slug_d0bba8_idx"),
        ),
    ]
