# Generated by Django 5.2.7 on 2026-02-04 11:14

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blog_slug_blog_blogs_blog_slug_d0bba8_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "last_modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Last modified",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="Is deleted"),
                ),
                (
                    "disabled",
                    models.BooleanField(default=False, verbose_name="Is disabled"),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the category"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category for the blog post",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blogs",
                to="blogs.blogcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["category"], name="blogs_blog_categor_399842_idx"
            ),
        ),
    ]
