# Generated by Django 5.2.7 on 2026-02-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_productrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="excerpt",
            field=models.TextField(
                blank=True, help_text="Short summary or excerpt of the product"
            ),
        ),
    ]
